language: java
jdk:
  - oraclejdk9

script:
 - # building libPlg
 - cd libPlg
 - ant
 - cd ..
 - # building libPlgStream
 - cp libPlg/dist/libPlg.jar libPlgStream/lib
 - cd libPlgStream
 - ant 
 - cd ..
 - # building plgResources
 - cd plgResources
 - ant
 - cd ..
 - # building libPlgVisualizer
 - cp libPlg/dist/libPlg.jar libPlgVisualizer/lib
 - cp plgResources/dist/plgResources.jar libPlgVisualizer/lib
 - cd libPlgVisualizer
 - ant 
 - cd ..
